### ISSUE TITLE
Rename old "KissIt" project and namespace to more professional name

### ISSUE THREAD

**Issue by CBielstein** [CBielstein/APRSsharp#4]
The old [KISS TNC](https://en.wikipedia.org/wiki/KISS_(TNC)) protocol library was written under the name `KissIt` as a joke. Let's rename that to something more appropriate.

For this ticket, do the following:
- [ ] Update `KissIt` project name to `KissTnc`
- [ ] Update class names as appropriate
- [ ] Update namespaces to `AprsSharp.Protocols`, `AprsSharp.DataSources` or something appropriate for this and other hardware/software interfaces for receiving and sending packets
- [ ] Update references in test project to point to new project
- [ ] Update test project name, class name, and namespaces along similar lines.

**Comment by CBielstein** [comment]
Let's please use `AprsSharp.Protocols` for the namespace here.

**Comment by eddywine** [comment]
@CBielstein I have made changes. I had changed the namespace to AprsSharp.Protocols but was giving a lot of errors since I had not build the project so I changed the namespaces to KissTnc. I did not know why the namespace was giving errors in this case
