### ISSUE TITLE
console application executable file size is too big, use trim to get the file size down

### ISSUE THREAD

**Issue by eddywine** [CBielstein/APRSsharp#50]

**Comment by CBielstein** [comment]
I'm not sure the relative importance of this issue. Introducing trim can reduce the file size but does increase developer effort as the developer has to manually trim a decent number of files and is [considered experimental even in .NET 5](https://docs.microsoft.com/en-us/dotnet/core/deploying/trim-self-contained). I would suggest that we close this for now and reopen it if we have a specific request from users to decrease file size in the future.

@eddywine What do you think?

**Comment by eddywine** [comment]
I think as you say, we can close this issue for now since in addition, the .exe file was not large enough to be unmanageable from the developer's side (60 MB). I also think we can also reopen the issue if we find ourselves having an output file that so large to cause download problems on the developer's side
