### ISSUE TITLE
Add top-level solution file

### ISSUE THREAD

**Issue by CBielstein** [CBielstein/APRSsharp#7]
Having a bunch of projects in the repository will get old to build and test. A .NET solution can be used to build and run tests on all projects at once. Create a new solution file with `dotnet new sln` at the top level of the directory. Use [`dotnet sln add`](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-sln) to add existing projects to the solution file.

For this issue to be done:
- [ ] Create `AprsSharp.sln`
- [ ] Add all current projects to the solution
- [ ] `dotnet build` and `dotnet test` from the root directory should succeed (and run tests for test comand)

**Comment by CBielstein** [comment]
Probably want to handle #4 and #5 first to save some extra trouble later with renames.

**Comment by CBielstein** [comment]
Add both KissIt & KissItTest to the sln.

**Comment by CBielstein** [comment]
leave it as a normal file at the root of the repository

So you should have

src/
test/
README.MD
AprsSharp.sln

All in the same directory.

**Comment by eddywine** [comment]
@CBielstein Will add this solution file after renaming APRS Parser code file # issue 5
